# Base de Dados Iris
#### Classificando uma iris em setosa, virginica ou versicolor.

### Importação das Bibliotecas

In [23]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import np_utils
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

### Importando a Base de Dados

In [3]:
dataframe = pd.read_csv('/content/drive/My Drive/iris.csv', encoding = 'utf-8', sep = ',')
previsores = dataframe.iloc[:, 0:4].values
classe = dataframe.iloc[:, 4].values

In [9]:
dataframe

sepal length  sepal width  petal length  petal width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [10]:
previsores

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [11]:
classe

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [12]:
classe_dummy

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

### Pré-processamento com a Base de Dados

In [4]:
labelencoder = LabelEncoder()
classe = labelencoder.fit_transform(classe)
classe_dummy = np_utils.to_categorical(classe)

|**Tipo**|**Variável Dummy**|
|:------:|:----------------:|
|Setosa|100|
|Virginica|010|
|Versicolor|001|

In [8]:
x_train, x_test, y_train, y_test = train_test_split(previsores, classe_dummy, 
                                                     test_size = 0.25)

In [13]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(112, 4)
(112, 3)
(38, 4)
(38, 3)


### Configuração da Rede Neural Artificial

In [14]:
classificador = Sequential()

classificador.add(Dense(units = 4, activation = 'relu', input_dim = 4))
classificador.add(Dense(units = 4, activation = 'relu'))
classificador.add(Dense(units = 3, activation = 'softmax', input_dim = 4))

In [15]:
classificador.compile(optimizer = 'adam', loss = 'categorical_crossentropy', 
                      metrics = ['categorical_accuracy'])

### Treinando a Rede Neural

In [16]:
classificador.fit(x_train, y_train, batch_size = 10, epochs = 1000)

Epoch 1/1000
112/112 [==============================] - 0s 3ms/step - loss: 1.4058 - categorical_accuracy: 0.3304
Epoch 2/1000
112/112 [==============================] - 0s 166us/step - loss: 1.3409 - categorical_accuracy: 0.3304
Epoch 3/1000
112/112 [==============================] - 0s 152us/step - loss: 1.2774 - categorical_accuracy: 0.3304
Epoch 4/1000
112/112 [==============================] - 0s 160us/step - loss: 1.2258 - categorical_accuracy: 0.3304
Epoch 5/1000
112/112 [==============================] - 0s 162us/step - loss: 1.1889 - categorical_accuracy: 0.3304
Epoch 6/1000
112/112 [==============================] - 0s 142us/step - loss: 1.1597 - categorical_accuracy: 0.3304
Epoch 7/1000
112/112 [==============================] - 0s 140us/step - loss: 1.1314 - categorical_accuracy: 0.3304
Epoch 8/1000
112/112 [==============================] - 0s 158us/step - loss: 1.1144 - categorical_accuracy: 0.3304
Epoch 9/1000
112/112 [==============================] - 0s 154us/step - lo

### Predição com a Base de Dados para Teste

In [17]:
resultado = classificador.evaluate(x_test, y_test)
print(resultado)

38/38 [==============================] - 0s 651us/step
[0.17062320707267836, 0.8947368264198303]


In [19]:
previsoes = classificador.predict(x_test)
previsoes = previsoes > 0.5
print(previsoes)

[[False False  True]
 [False False  True]
 [False False  True]
 [ True False False]
 [False False  True]
 [False False  True]
 [False False  True]
 [ True False False]
 [False  True False]
 [ True False False]
 [False False  True]
 [False False  True]
 [ True False False]
 [False False  True]
 [False  True False]
 [ True False False]
 [False False  True]
 [ True False False]
 [ True False False]
 [False False  True]
 [ True False False]
 [False  True False]
 [False  True False]
 [False  True False]
 [False False  True]
 [False False  True]
 [False  True False]
 [False False  True]
 [ True False False]
 [False False  True]
 [False  True False]
 [ True False False]
 [False  True False]
 [ True False False]
 [ True False False]
 [False  True False]
 [ True False False]
 [False False  True]]


In [20]:
y_test2 = [np.argmax(t) for t in y_test]
previsoes2 = [np.argmax(t) for t in previsoes]

In [21]:
y_test2

[2,
 2,
 2,
 0,
 2,
 2,
 1,
 0,
 1,
 0,
 2,
 2,
 0,
 1,
 1,
 0,
 2,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 2,
 2,
 1,
 2,
 0,
 2,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 2]

In [22]:
previsoes2

[2,
 2,
 2,
 0,
 2,
 2,
 2,
 0,
 1,
 0,
 2,
 2,
 0,
 2,
 1,
 0,
 2,
 0,
 0,
 2,
 0,
 1,
 1,
 1,
 2,
 2,
 1,
 2,
 0,
 2,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 2]

In [24]:
matriz = confusion_matrix(previsoes2, y_test2)
print(matriz)

[[12  1  0]
 [ 0  9  0]
 [ 0  3 13]]


### Alguma Dúvida? Entre em Contato Comigo:

- [Me envie um e-mail](mailto:alysson.barbosa@ee.ufcg.edu.br);